### ISSUE TITLE
Add to Tracing's "Related Crates" list?

### ISSUE THREAD

**Issue by hawkw** [gfx-rs/subscriber#1]
:wave: Hi! Thanks for your work on this library, this is really cool!

I'm just stopping by to let you know that, in the `tracing` repo, we have [a list of related crates](https://github.com/tokio-rs/tracing#related-crates) to help users discover other `tracing` crates in the ecosystem. If you're interested, we'd love a PR to add this library to that list! I've definitely seen people asking about a `tracing` subscriber that emits the Chrome trace format in the past, so I imagine that a lot of folks would be excited to use this.

Thanks again for your work on this crate! :)

**Comment by kvark** [comment]
It's super fresh, and very utilitarian. We've yet to see how it proves to be useful. Honestly, I'd expect tracing ecosystem to already provide all of this.
Anyhow, I don't mind this added to the list. @cwfitzgerald has the last word ;)

**Comment by cwfitzgerald** [comment]
That would be lovely! I'll work on a PR :)

Back when I started this project, we discussed the possibility of upstreaming the work with chrome to (somewhere?) so it would have greater use. I am definitely still interested in doing this if you are!

The only real issue is this special `trace` field on events, allowing them and only them to show up in chrome traces. We use it to [mark when the frame has finished presenting](https://github.com/gfx-rs/wgpu/blob/master/wgpu-core/src/swap_chain.rs#L279). This seems application specific, so might not belong upstream. We would still want this functionality _somehow_, but what that would look like I have no idea.

**Comment by hawkw** [comment]
> The only real issue is this special `trace` field on events, allowing them and only them to show up in chrome traces. We use it to [mark when the frame has finished presenting](https://github.com/gfx-rs/wgpu/blob/master/wgpu-core/src/swap_chain.rs#L279). This seems application specific, so might not belong upstream. We would still want this functionality _somehow_, but what that would look like I have no idea.

Ah, okay, I hadn't realized that. There are a couple designs you could do to make it more generally applicable:
1. Continue using the special field for events that should be output to the Chrome trace, but give it a documented, conventional name that's namespaced to make it clear that it's for Chrome tracing. Something like `chrome.trace.enable = true` or similar.
   
   This would be the easiest solution, but it has some downsides --- it doesn't work great for events in library code where the library has no idea if the user is using the Chrome trace layer (or even if it's running in a browser at all). And, if you do put the special field on events, it adds noise when those events are output in other formats.

2. Implement some kind of filtering for selecting which events should be output to the Chrome trace. You could essentially implement something like [`EnvFilter`](https://docs.rs/tracing-subscriber/0.2.11/tracing_subscriber/filter/struct.EnvFilter.html) (or a subset of `EnvFilter`) and use it to determine whether to emit a span/event to the Chrome trace. This seems like a much better solution for the user, since the end user application could determine which events should be sent to Chrome, and libraries wouldn't have to care, _and_ the filter could be configured at runtime. On the other hand, it would be a bit more work.

3. Wait for per-layer filtering (https://github.com/tokio-rs/tracing/issues/302) to be implemented upstream. We want to eventually have an abstraction for wrapping individual layers in a filter that applies only to _that_ layer. This would allow the application to configure arbitrary filters for the Chrome trace subscriber, like option (2), but without requiring the layer to implement its own custom filtering. The downside is...you'd have to wait until I actually have the time to finish that. :P
